PyTorch 공식 사이트와 PyTorch로 시작하는 딥러닝 입문을 토대로 공부하였습니다.

PyTorch 공식 사이트: https://tutorials.pytorch.kr/beginner/basics/quickstart_tutorial.html

PyTorch로 시작하는 딥러닝 입문:https://wikidocs.net/57168

# Tensor

PyTorch는 Tensor라는 특수한 자료구조를 사용하는데, 배열과 행렬이랑 매우 비슷하다.

PyTorch에서는 Tensor를 사용하여 모델의 입력(input)과 출력(output), 그리고 모델의 매개변수들을 부호화(encode)한다.

Tensor는 Numpy의 ndarray와 유사하고, 자동 미분에 최적화되어 있다.

In [2]:
import torch
import numpy as np

## Tensor 초기화

Tensor는 데이터로부터 직접 생성할 수도 있고, NumPy 배열로부터 생성할 수도 있다.

데이터로부터 직접 Tensor를 생성하면, 데이터의 자료형은 자동으로 유추한다.

NumPy 배열을 이용하여 Tensor를 생성할 수도 있지만, 그 반대인 Tensor를 통해서 NumPy 배열을 생성할 수도 있다.

Tensor에서 dim = 0은 행 차원의 제거이고, dim = 1 or -1은 열 차원의 제거이다. 

즉, dim = 0은 가로 행기준 연산, dim = 1 or -1은 세로 열기준 연산이다.

In [5]:
# 데이터로부터 직접 생성하기

data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
# NumPy 배열로부터 생성하기

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

명시적으로 재정의(override)하지 않는다면, 인자로 주어진 Tensor의 속성을 유지한다.

즉, 주어진 텐서와 같은 모양과 자료형을 계속 유지한다는 것이다.

In [9]:
x_ones = torch.ones_like(x_data) # x_data와 같은 속성을 유지하면서 값을 1로 채우는 것
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data와 같은 속성을 유지하면서 값을 랜덤하게 채우는 것
print(f"Random Tensor: \n {x_rand} \n")

x_zero = torch.zeros_like(x_data, dtype=torch.float) # x_data와 같은 속성을 유지하면서 값을 0으로 채우는 것
print(f"Random Tensor: \n {x_zero} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5166, 0.6123],
        [0.0686, 0.7618]]) 

Random Tensor: 
 tensor([[0., 0.],
        [0., 0.]]) 



기존에 존하는 Tensor의 속성을 이용하여 데이터를 편집할 수도 있지만, 처음부터 Tensor의 차원을 결정하여서 만들 수도 있다.

In [10]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7570, 0.7762, 0.9068],
        [0.8874, 0.4538, 0.8843]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Tensor의 속성(Attribute)

Tensor의 속성을 확인하는 방법은 3가지가 있다.

shape, dtype, device

In [15]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Tensor의 연산(Operation)

기본적으로 Tensor의 연산은 CPU와 GPU를 이용하여서 할 수 있다.

일반적으로 GPU가 더 빠른 연산을 가능하게 해주기 때문에 GPU로 Tensor를 이동시켜 연산하는 방법을 사용하면 더 빠른 연산이 가능하다.

Tensor를 만들면 기본적으로 CPU에 생성된다. 그렇기 때문에 .to 메소드를 사용하여 GPU로 이동을 시켜야한다.

In [17]:
# GPU가 존재하면 텐서를 이동합니다
# 아쉽게도 내 노트북에서는 GPU가 없다....
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

Tensor의 인덱싱과 슬라이싱은 NumPy와 매우 비슷하다.

그렇기 때문에 Numpy를 사용하듯이 사용하면 거의 다 된다.

In [18]:
tensor = torch.ones(4, 4) #1로 채워져있는 4x4의 tensor 생성

print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0 # 2번째 column을 0으로 채우기
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Tensor 합치기

Tensor를 합치는 방법에는 torch.cat과 torch.stack이 존재한다.

두가지 방법은 미묘하게 다른데, torch.stack은 Stacking이라고 불리며, 무언가를 쌓는다는 뜻이다.

즉, Stacking은 순차적으로 벡터를 쌓는 작업을 하는 것이다.

아래 코드는 같은 작업을 한 것이지만, torch.cat을 사용했을때 더 복잡해진 모습을 확인 할 수 있다.

In [21]:
# Stacking
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [22]:
# Concatenate
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


Stacking은 추가적으로 dim을 인자로 줄 수 있다.

예를 들어 dim=1은 두번째 차원이 증가하도록 Stack하라는 의미이다.

In [29]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


### 산술연산

Tensor 행렬 곱(matrix muliplication)

Tensor 요소별 곱(element-wise product)

*행렬 곱과 요소별 곱의 차이는 행렬 곲은 행렬 곱셈이지만, 요소별 곱셈은 같은 위치에 위치해 있는 원소끼리 곱하는 것이다.

Tensor 요소 합

Tensor에 특정 수 연산(바꿔치기 연산이라 부름)

In [36]:
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [37]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
y1 = tensor @ tensor.T # tensor와 tensor의 전치행렬 곱
y2 = tensor.matmul(tensor.T) # tensor와 tensor의 전치행렬 곱

y3 = torch.rand_like(tensor) # 행렬 곱 결과를 저장할 tensor 생성
torch.matmul(tensor, tensor.T, out=y3) # tensor와 tensor 전치행렬을 곱하여 결과를 y3에 저장

print(y1)
print(y2)
print(y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [35]:
# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z2)
print(z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [39]:
# 단일요소(single-element)의 모든 값을 하나로 집계하여 요소가 하나인 텐서로 만듬
# item()을 사용하여 숫자 값으로 변환해야지만 사용이 가능
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(12.)
12.0 <class 'float'>


In [40]:
# tensor에 특정 수를 연산하는 것 바꿔치기(in-place)연산이라 부르며, 기록이 즉시 삭제되어 도함수 계산에 문제가 될 수 있음.
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## 뷰(View) - 원소의 수를 유지하면서 텐서의 크기를 변경하는 것

Tensor의 View는 NumPy의 Reshape와 같은 역할을 한다,

즉, 특정 차원의 Tensor를 다른 차원으로 변경할때 사용한다.

In [3]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


### 차원 변경

위의 Tensor는 3차원의 Tensor이다. 이를 2차원으로 변경시켜 볼 것이다.

In [4]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


fit.view([-1, 3])에서 -1은 첫번째 차원은 Pytorch가 알아서 설정하라는 의미이고, 두번째 차원은 3으로 하라는 이야기이다.

결과적으로 (4,3)의 크기를 가지는 Tensor로 바꾸었다.

이때, 기본적인 규칙이 있는데 변경 전과 변경 후의 Tensor 안에 원소 개수가 유지되어야한다는 것이다.

그렇기 때문에 앞서 (2,2,3)에서 (4,3)으로 변경된 이유는 해당 차원의 곱의 결과가 같아야하기 때문이다.

### Squeeze - 1인 차원을 제거

스퀴즈는 차원이 1인 경우에 해당 차원을 제거하는 것이다.

예를들어 (2,1,3)이라는 차원이 있을때 가운데 있는 1을 제거하는 것이다.

In [5]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [6]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze - 특정 위치에 1인 차원을 추가

Squeeze가 1인 차원을 제거하는 것인 반면 Unsqueeze는 특정위치에 1인 차원을 추가하는 것이다.

In [8]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [9]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])
